/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/drip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drip tokens to users (testing/development faucet) */
        post: operations["drip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get information about tokens, markets, etc. */
        post: operations["info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute trades (place/cancel orders) */
        post: operations["trade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get user-specific data (orders, balances, trades) */
        post: operations["user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            message: string;
            /** Format: int64 */
            timestamp: number;
        };
        Balance: {
            amount: number;
            open_interest: number;
            token_ticker: string;
            /** Format: date-time */
            updated_at: string;
            user_address: string;
        };
        DripErrorResponse: {
            code: string;
            error: string;
        };
        /** @description Drip request with type discriminator */
        DripRequest: {
            amount: string;
            signature: string;
            token_ticker: string;
            /** @enum {string} */
            type: "faucet";
            user_address: string;
        };
        /** @description Drip response with type discriminator */
        DripResponse: {
            amount: string;
            new_balance: string;
            token_ticker: string;
            /** @enum {string} */
            type: "faucet";
            user_address: string;
        };
        InfoErrorResponse: {
            code: string;
            error: string;
        };
        /** @description Info request with type discriminator */
        InfoRequest: {
            ticker: string;
            /** @enum {string} */
            type: "token_details";
        } | {
            market_id: string;
            /** @enum {string} */
            type: "market_details";
        } | {
            /** @enum {string} */
            type: "all_markets";
        } | {
            /** @enum {string} */
            type: "all_tokens";
        };
        /** @description Info response with type discriminator */
        InfoResponse: {
            token: components["schemas"]["Token"];
            /** @enum {string} */
            type: "token_details";
        } | {
            market: components["schemas"]["Market"];
            /** @enum {string} */
            type: "market_details";
        } | {
            markets: components["schemas"]["Market"][];
            /** @enum {string} */
            type: "all_markets";
        } | {
            tokens: components["schemas"]["Token"][];
            /** @enum {string} */
            type: "all_tokens";
        };
        Market: {
            base_ticker: string;
            id: string;
            lot_size: number;
            /** Format: int32 */
            maker_fee_bps: number;
            min_size: number;
            quote_ticker: string;
            /** Format: int32 */
            taker_fee_bps: number;
            tick_size: number;
        };
        Order: {
            /** Format: date-time */
            created_at: string;
            filled_size: number;
            /** Format: uuid */
            id: string;
            market_id: string;
            order_type: components["schemas"]["OrderType"];
            price: number;
            side: components["schemas"]["Side"];
            size: number;
            status: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            updated_at: string;
            user_address: string;
        };
        /** @enum {string} */
        OrderStatus: "pending" | "filled" | "partially_filled" | "cancelled";
        /** @enum {string} */
        OrderType: "limit" | "market";
        /** @enum {string} */
        Side: "buy" | "sell";
        Token: {
            /** Format: int32 */
            decimals: number;
            name: string;
            ticker: string;
        };
        Trade: {
            buyer_address: string;
            /** Format: uuid */
            buyer_order_id: string;
            /** Format: uuid */
            id: string;
            market_id: string;
            price: number;
            seller_address: string;
            /** Format: uuid */
            seller_order_id: string;
            size: number;
            /** Format: date-time */
            timestamp: string;
        };
        TradeErrorResponse: {
            code: string;
            error: string;
        };
        /** @description Trade request with type discriminator */
        TradeRequest: {
            market_id: string;
            order_type: components["schemas"]["OrderType"];
            price: string;
            side: components["schemas"]["Side"];
            signature: string;
            size: string;
            /** @enum {string} */
            type: "place_order";
            user_address: string;
        } | {
            order_id: string;
            signature: string;
            /** @enum {string} */
            type: "cancel_order";
            user_address: string;
        };
        /** @description Trade response with type discriminator */
        TradeResponse: {
            order: components["schemas"]["Order"];
            trades: components["schemas"]["Trade"][];
            /** @enum {string} */
            type: "place_order";
        } | {
            order_id: string;
            /** @enum {string} */
            type: "cancel_order";
        };
        UserErrorResponse: {
            code: string;
            error: string;
        };
        /** @description User request with type discriminator */
        UserRequest: {
            /** Format: int32 */
            limit?: number | null;
            market_id?: string | null;
            status?: string | null;
            /** @enum {string} */
            type: "orders";
            user_address: string;
        } | {
            /** @enum {string} */
            type: "balances";
            user_address: string;
        } | {
            /** Format: int32 */
            limit?: number | null;
            market_id?: string | null;
            /** @enum {string} */
            type: "trades";
            user_address: string;
        };
        /** @description User response with type discriminator */
        UserResponse: {
            orders: components["schemas"]["Order"][];
            /** @enum {string} */
            type: "orders";
        } | {
            balances: components["schemas"]["Balance"][];
            /** @enum {string} */
            type: "balances";
        } | {
            trades: components["schemas"]["Trade"][];
            /** @enum {string} */
            type: "trades";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    drip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DripRequest"];
            };
        };
        responses: {
            /** @description Tokens dripped successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripErrorResponse"];
                };
            };
            /** @description Invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripErrorResponse"];
                };
            };
            /** @description Token not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripErrorResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health check response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoErrorResponse"];
                };
            };
        };
    };
    trade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeErrorResponse"];
                };
            };
            /** @description Invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeErrorResponse"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeErrorResponse"];
                };
            };
        };
    };
    user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserErrorResponse"];
                };
            };
            /** @description User or resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserErrorResponse"];
                };
            };
        };
    };
}
